version: 2.1
orbs:
  qlty: qltysh/qlty-orb@0.0.3
jobs:
  build:
    docker:
      - image: cimg/ruby:3.1
    steps:
      - checkout

      - run:
          name: Set up Ruby
          command: |
            gem install bundler
            bundle config set --local path 'vendor/bundle'
            bundle install --jobs=4 --retry=3

      - run:
          name: Run tests
          command: bundle exec rspec --require spec_helper
          
      - qlty/coverage_publish:
          incomplete: true
          files: coverage/coverage.json

      - qlty/coverage_publish:
          incomplete: true
          files: coverage/coverage.json

      - qlty/coverage_complete

workflows:
  version: 2
  main:
    jobs:
      - build
