version: 2.1
orbs:
  qlty: qltysh/qlty-orb@0.0.2
jobs:
  build:
    docker:
      - image: cimg/ruby:3.1
    steps:
      - checkout

      # Set up Ruby environment
      - run:
          name: Set up Ruby
          command: |
            gem install bundler
            bundle config set --local path 'vendor/bundle'
            bundle install --jobs=4 --retry=3

      # Run the default task
      - run:
          name: Run tests
          command: bundle exec rspec --require spec_helper
          
      # Qlty Coverage Orb
      - qlty/coverage_publish:
          files: coverage/coverage.json

workflows:
  version: 2
  main:
    jobs:
      - build
